GET http://localhost:3000/api/v1/

### 

POST http://localhost:3000/api/v1/users/signup
Content-Type: application/json

{
    "name":{
        "first": "Pratik",
        "last": "Chavan"
    },
    "email": "pchavan4@buffalo.edu",
    "password": "pratik@123"
}

###
POST http://localhost:3000/api/v1/users/sendOtp
Content-Type: application/json

{
    "user":{"email": "pchavan4@buffalo.edu"},
    "resend": "true"
}


###
POST http://localhost:3000/api/v1/users/verifyEmail
Content-Type: application/json

{
    "email": "pchavan4@buffalo.edu",
    "otp": "CrAUJJ"
}

###
POST http://localhost:3000/api/v1/users/login
Content-Type: application/json

{
    "email": "pchavan4@buffalo.edu",
    "password": "pratik@123"
}

### 

POST http://localhost:3000/api/v1/tasks/create
Content-Type: application/json

{
    "email": "chavanpratik.pc@gmail.com",
    "name": "Resolve a bug task",
    "body": "Task body"
}

### 
GET http://localhost:3000/api/v1/tasks/show
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBjaGF2YW40QGJ1ZmZhbG8uZWR1IiwiaWF0IjoxNjc2NDEwMTg4LCJleHAiOjE2NzY0MTAyMTh9.xXZZt-Vt33uL2BWpZnL5pxL1sMYucc-o1uzHnXXVyHI