name: Deploying

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: authenticating AWS
        env:
          HOSTNAME: ${{ secrets.AWS_HOST }}
          USER_NAME: ${{ secrets.AWS_USER }}
          PRIVATE_KEY: ${{ secrets.AWS_KEY }}
        run: |
          echo "$PRIVATE_KEY" > PRIVATE_KEY && chmod 600 PRIVATE_KEY
          ssh -o StrictHostKeyChecking=no -i PRIVATE_KEY ${USER_NAME}@${HOSTNAME}  
          ' #Now we have got the access of EC2 and we will start the deploy .
          cd /home/ubuntu/CounterApp &&
          git checkout master &&
          git fetch --all &&
          git reset --hard origin/master &&
          git pull origin master &&
          docker-compose -f docker-compose.prod.yml up -d --build'
